title: "Homepage"
description: "Dúo Díptico: música en vivo con voz y guitarra acústica, pop-rock y clásicos para bodas, eventos privados y conciertos íntimos en toda España."
image: https://duodiptico.github.io/landing-page/static/img/social_card_cropped.jpeg   # 1200 × 630 px ideal
url: "https://duodiptico.github.io"   # sin slash final
baseurl: "/landing-page"              # nombre del repo con slash inicial

plugins:
  - jekyll-seo-tag   # ← gem 1: auto meta tags
  - jekyll-sitemap   # ← gem 2: /sitemap.xml for search engines